"""VNCCS Nodes - ComfyUI nodes for visual novel character creation."""

try:
    from .emotion_generator_v2 import NODE_CLASS_MAPPINGS as EMOTION_GENERATOR_V2_MAPPINGS
    from .vnccs_control_center import NODE_CLASS_MAPPINGS as VNCCS_CONTROL_CENTER_MAPPINGS
    from .character_generator import NODE_CLASS_MAPPINGS as CHARACTER_GENERATOR_MAPPINGS
    from .character_creator_v2 import NODE_CLASS_MAPPINGS as CHARACTER_CREATOR_V2_MAPPINGS
    from .style_preview_test import NODE_CLASS_MAPPINGS as STYLE_PREVIEW_TEST_MAPPINGS
    from .character_cloner import NODE_CLASS_MAPPINGS as CHARACTER_CLONER_MAPPINGS
    from .clothes_designer import NODE_CLASS_MAPPINGS as CLOTHES_DESIGNER_MAPPINGS
    from .vnccs_qwen_encoder import NODE_CLASS_MAPPINGS as VNCCS_QWEN_ENCODER_MAPPINGS

    from .emotion_generator_v2 import NODE_DISPLAY_NAME_MAPPINGS as EMOTION_GENERATOR_V2_DISPLAY_MAPPINGS
    from .vnccs_control_center import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_CONTROL_CENTER_DISPLAY_MAPPINGS
    from .character_generator import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_GENERATOR_DISPLAY_MAPPINGS
    from .character_creator_v2 import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_CREATOR_V2_DISPLAY_MAPPINGS
    from .style_preview_test import NODE_DISPLAY_NAME_MAPPINGS as STYLE_PREVIEW_TEST_DISPLAY_MAPPINGS
    from .character_cloner import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_CLONER_DISPLAY_MAPPINGS
    from .clothes_designer import NODE_DISPLAY_NAME_MAPPINGS as CLOTHES_DESIGNER_DISPLAY_MAPPINGS
    from .vnccs_qwen_encoder import NODE_DISPLAY_NAME_MAPPINGS as VNCCS_QWEN_ENCODER_DISPLAY_MAPPINGS

    NODE_CLASS_MAPPINGS = {
        **EMOTION_GENERATOR_V2_MAPPINGS,
        **VNCCS_CONTROL_CENTER_MAPPINGS,
        **CHARACTER_GENERATOR_MAPPINGS,
        **CHARACTER_CREATOR_V2_MAPPINGS,
        **STYLE_PREVIEW_TEST_MAPPINGS,
        **CHARACTER_CLONER_MAPPINGS,
        **CLOTHES_DESIGNER_MAPPINGS,
        **VNCCS_QWEN_ENCODER_MAPPINGS,
    }

    NODE_DISPLAY_NAME_MAPPINGS = {
        **EMOTION_GENERATOR_V2_DISPLAY_MAPPINGS,
        **VNCCS_CONTROL_CENTER_DISPLAY_MAPPINGS,
        **CHARACTER_GENERATOR_DISPLAY_MAPPINGS,
        **CHARACTER_CREATOR_V2_DISPLAY_MAPPINGS,
        **STYLE_PREVIEW_TEST_DISPLAY_MAPPINGS,
        **CHARACTER_CLONER_DISPLAY_MAPPINGS,
        **CLOTHES_DESIGNER_DISPLAY_MAPPINGS,
        **VNCCS_QWEN_ENCODER_DISPLAY_MAPPINGS,
    }
except Exception as e:
    import traceback
    print(f"❌ [VNCCS] CRITICAL REGISTRATION ERROR in nodes/__init__.py: {e}")
    traceback.print_exc()
    raise RuntimeError(f"[VNCCS] Node registration failed: {e}") from e

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
